### PR TITLE
add "," to "Hello, world"

### PR DESCRIPTION
**Pull request by Allicolyer**
Hey I spent some time trying to figure out why your `reduce` function in `test.js` doesn't return false when there is a failing test but I couldn't figure it out 🤷

### CODE REVIEW

**Comment by georgemandis** [comment]
The test script isn't the most well-written thing in the world... I think it does return `false`, but the result doesn't stop the test from continuing to run through the rest of them. When I run it locally on your old version of the script it (correctly) tells me it doesn't pass the test?

Screen Shot 2020-05-17 at 9 03 28 PM

**Comment by Allicolyer** [comment]
oh! I saw that. I was talking about this part:
```
console.log(
  results
    ? "😀 Tests passed! All scripts returned 'Hello, World'"
    : "☹️ Tests failed! One or more scripts did not return 'Hello, World'"
);
```

**Comment by georgemandis** [comment]
Oh! Good catch :)

Hmm. I'm curious now too...

**Comment by Allicolyer** [comment]
Tell me if you figure it out!

I also found that `previous` first becomes false for `src/009-hello-world.js`. 

If you `console.log(require(current)() === "Hello, World")` for 009, you get `false`, but it is passing the test and `returnsHelloWorld` is true.

This returns also false for that example:
```
console.log(returnsHelloWorld === (require(current)() === "Hello, World"))
```
but it is true for every other example, which is what you would expect.

I feel like this is a weird JavaScript thing that you would know about 🤷

**Comment by georgemandis** [comment]
I think I figured it out! There were a few curious things happening, including the issue with `009-hello-world.js` that you found:

### The 009 Bug

The way I wrote `009` it only works correctly the **first** time you call the function because it's modifying it's own properties and appending to `this.returnValue` every iteration. The first time you call it it returns "Hello, World" and the second time it returns "Hello, WorldHello, World."

Ignoring the silliness of that design for a minute, the test passed the first time it was called (Hence no ❌ fail in the output) **but** it failed and returned a false in the reduce function the *second* time it was called! I fixed this by updating the test script to only require and call the function once, make sure the output is 'Hello, World' and store that to pass along to the reducer. 

### Ghosts of Scripts Not Yet Born 👻

But there was another problem—I lazily have it check for scripts that don't exist yet (see the comments in the code about writing it on an airplane...). For those I had to default to returning `true` which is a bug! 

Basically, the tests always passed–as you noted–at least according to the final output message. This made me realize I almost never looked at the final output message...

### Node Versioning Conundrum

The third curious thing that doesn't play into this: `023` only works in node 11.4 and the more recently committed one `041` won't work in that version because it doesn't include `globalThis` yet. It's my fault for not clearly specifying a version to pin this project to... and now I have a quandary. @iakshay and I spent a lot of time getting `023` to work... It's pure vanity, but I'm struggling to find a way to make both pass! Haha. I'd rewrite Akshay and I's but... [look at it](https://github.com/georgemandis/101-hello-worlds/blob/master/src/023-hello-world.js). It gives me a headache just thinking about it.

**Pull request merged**
